#!/bin/sh


# Set decoration geometry
berryc border_width       0
berryc inner_border_width 5
berryc title_height       30
berryc top_gap            30

# Set decoration colors
berryc focus_color         FFFAFA
berryc unfocus_color       FFFAFA
berryc inner_focus_color   A0B4FA
berryc inner_unfocus_color 282C34
berryc text_focus_color    000064
berryc text_unfocus_color  A0B4FA

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Cascadia Code-8"
